### PR TITLE
CCF-9079 - CLI generators for windows

### PR DESCRIPTION
**Pull request by dschueller-cs**
* Restructured the generators folder to separate scripts into os specific folders
* Changed the generator code to use the correct folder for the current OS
* Added deployment/build scripts for Windows/Powershell

### CODE REVIEW

**Comment by cdraper-CS** [comment]
My problems above were because I had the old template files still in the directory.  I regenerated and ran locally with an updated CLI. All of the generates succeeded on OSX and generated scripts that I could use to deploy/test. I did also run the CLI skill, dataset and connection generate tests. All worked except node 8 which failed with a weird exception even though it works when run manually. I'm approving the code change because I think there must be something up with either the test or my setup and it will be easier to investigate when the library is in npm.

**Comment by vadan-cs** [comment]
Testing in osX: 
- `cortex skills generate` works 
- `cortex connections generate` works
- `cortex datasets generates` gives me ```✗ ./bin/cortex.js datasets generate
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Forbidden
    at Request.callback (/Users/vadan/c5/generator-cortex/node_modules/superagent/lib/node/index.js:696:15)
    at parser (/Users/vadan/c5/generator-cortex/node_modules/superagent/lib/node/index.js:906:18)
    at IncomingMessage.res.on (/Users/vadan/c5/generator-cortex/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)```

**Comment by dschueller-cs** [comment]
I just tried generating a dataset with the original branch (unmodified by me) and it has the same error, so I dont think its something I introduced.

All I did was make windows versions of the scripts that were there, so if it didnt work before, I wouldnt expect it to work now.

I'll take a look and see if I can figure out what's going on.

**Comment by dschueller-cs** [comment]
The above dataset error appears to happen in the current released version of the cortex CLI.  Can someone confirm that this is the case for them as well?

**Comment by dschueller-cs** [comment]
> How does one generate a job? generators/job/templates/function/scripts/win32/deploy-job.bat

It looks like the jobs generator was never hooked up in the original CLI.

We should probably discuss if we should just remove jobs from the CLI given that they have been replaced by actions?

**Pull request merged**
